[package]
name = "spreadsheets"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
tokio = { version = "1.39.3", features = ["full"] }
redis = { version = "0.26.1", features = ["tokio-comp"] }
